version: "3.3"

services:
  categroy-service:
    build: ./category-service
    ports:
      - 6000:6000
      - 6001:6001
      - 6002:6002
  product-service:
    build: ./product-service
    ports:
    - 7000:7000
    - 7001:7001
    - 7002:7002
  postgres-ps:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
